language: clojure
lein: lein2
install: cd leiningen-core; lein install; lein classpath | tail -n 1 > .lein-bootstrap; cd ..
script: lein with-profile travis-ci test
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database babel;' -U postgres
  - psql -U postgres babel < src/sql/babel.sql
sudo: false

